# Generated by Django 4.1 on 2022-09-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colab_nombre', models.CharField(max_length=40)),
                ('colab_apellido', models.CharField(max_length=40)),
                ('colab_edad', models.IntegerField()),
                ('colab_fecha_ingreso', models.DateField()),
                ('colab_categoria_venta', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='compradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_nombre', models.CharField(max_length=40)),
                ('buyer_apellido', models.CharField(max_length=40)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_direccion', models.CharField(max_length=70)),
                ('buyer_tlf', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='sellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_nombre', models.CharField(max_length=40)),
                ('seller_categoria', models.CharField(max_length=50)),
                ('seller_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
