# Generated by Django 4.1 on 2022-09-26 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appnum1', '0002_alter_compradores_buyer_tlf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboradores',
            name='colab_fecha_ingreso',
        ),
    ]
