# Generated by Django 4.1 on 2022-09-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appnum1', '0003_remove_colaboradores_colab_fecha_ingreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compradores',
            old_name='buyer_apellido',
            new_name='b_apellido',
        ),
        migrations.RenameField(
            model_name='compradores',
            old_name='buyer_direccion',
            new_name='b_direccion',
        ),
        migrations.RenameField(
            model_name='compradores',
            old_name='buyer_email',
            new_name='b_email',
        ),
        migrations.RenameField(
            model_name='compradores',
            old_name='buyer_nombre',
            new_name='b_nombre',
        ),
        migrations.RenameField(
            model_name='compradores',
            old_name='buyer_tlf',
            new_name='b_tlf',
        ),
    ]
