# Generated by Django 4.1 on 2022-09-27 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appnum1', '0004_rename_buyer_apellido_compradores_b_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compradores',
            name='b_nombre',
        ),
    ]
