# Generated by Django 4.1 on 2022-09-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appnum1', '0006_buyers_delete_compradores'),
    ]

    operations = [
        migrations.CreateModel(
            name='colabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colab_legajo', models.IntegerField()),
                ('colab_nombre', models.CharField(max_length=40)),
                ('colab_apellido', models.CharField(max_length=40)),
                ('colab_edad', models.IntegerField()),
                ('colab_categoria_venta', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='colaboradores',
        ),
    ]
